#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "Reboot|> Shutdown")"
            case "$MENU" in
                Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
